--상점 50개 더미 데이터 + 점원 400개 더미 데이터
INSERT INTO store (name, phone) VALUES ('name 001', 'phone 001');
INSERT INTO store (name, phone) VALUES ('name 002', 'phone 002');
INSERT INTO store (name, phone) VALUES ('name 003', 'phone 003');
INSERT INTO store (name, phone) VALUES ('name 004', 'phone 004');
INSERT INTO store (name, phone) VALUES ('name 005', 'phone 005');
INSERT INTO store (name, phone) VALUES ('name 006', 'phone 006');
INSERT INTO store (name, phone) VALUES ('name 007', 'phone 007');
INSERT INTO store (name, phone) VALUES ('name 008', 'phone 008');
INSERT INTO store (name, phone) VALUES ('name 009', 'phone 009');
INSERT INTO store (name, phone) VALUES ('name 010', 'phone 010');
INSERT INTO store (name, phone) VALUES ('name 011', 'phone 011');
INSERT INTO store (name, phone) VALUES ('name 012', 'phone 012');
INSERT INTO store (name, phone) VALUES ('name 013', 'phone 013');
INSERT INTO store (name, phone) VALUES ('name 014', 'phone 014');
INSERT INTO store (name, phone) VALUES ('name 015', 'phone 015');
INSERT INTO store (name, phone) VALUES ('name 016', 'phone 016');
INSERT INTO store (name, phone) VALUES ('name 017', 'phone 017');
INSERT INTO store (name, phone) VALUES ('name 018', 'phone 018');
INSERT INTO store (name, phone) VALUES ('name 019', 'phone 019');
INSERT INTO store (name, phone) VALUES ('name 020', 'phone 020');
INSERT INTO store (name, phone) VALUES ('name 021', 'phone 021');
INSERT INTO store (name, phone) VALUES ('name 022', 'phone 022');
INSERT INTO store (name, phone) VALUES ('name 023', 'phone 023');
INSERT INTO store (name, phone) VALUES ('name 024', 'phone 024');
INSERT INTO store (name, phone) VALUES ('name 025', 'phone 025');
INSERT INTO store (name, phone) VALUES ('name 026', 'phone 026');
INSERT INTO store (name, phone) VALUES ('name 027', 'phone 027');
INSERT INTO store (name, phone) VALUES ('name 028', 'phone 028');
INSERT INTO store (name, phone) VALUES ('name 029', 'phone 029');
INSERT INTO store (name, phone) VALUES ('name 030', 'phone 030');
INSERT INTO store (name, phone) VALUES ('name 031', 'phone 031');
INSERT INTO store (name, phone) VALUES ('name 032', 'phone 032');
INSERT INTO store (name, phone) VALUES ('name 033', 'phone 033');
INSERT INTO store (name, phone) VALUES ('name 034', 'phone 034');
INSERT INTO store (name, phone) VALUES ('name 035', 'phone 035');
INSERT INTO store (name, phone) VALUES ('name 036', 'phone 036');
INSERT INTO store (name, phone) VALUES ('name 037', 'phone 037');
INSERT INTO store (name, phone) VALUES ('name 038', 'phone 038');
INSERT INTO store (name, phone) VALUES ('name 039', 'phone 039');
INSERT INTO store (name, phone) VALUES ('name 040', 'phone 040');
INSERT INTO store (name, phone) VALUES ('name 041', 'phone 041');
INSERT INTO store (name, phone) VALUES ('name 042', 'phone 042');
INSERT INTO store (name, phone) VALUES ('name 043', 'phone 043');
INSERT INTO store (name, phone) VALUES ('name 044', 'phone 044');
INSERT INTO store (name, phone) VALUES ('name 045', 'phone 045');
INSERT INTO store (name, phone) VALUES ('name 046', 'phone 046');
INSERT INTO store (name, phone) VALUES ('name 047', 'phone 047');
INSERT INTO store (name, phone) VALUES ('name 048', 'phone 048');
INSERT INTO store (name, phone) VALUES ('name 049', 'phone 049');
INSERT INTO store (name, phone) VALUES ('name 050', 'phone 050');

INSERT INTO clerk (name, store_id) VALUES ('name 0001', 1);
INSERT INTO clerk (name, store_id) VALUES ('name 0002', 2);
INSERT INTO clerk (name, store_id) VALUES ('name 0003', 3);
INSERT INTO clerk (name, store_id) VALUES ('name 0004', 4);
INSERT INTO clerk (name, store_id) VALUES ('name 0005', 5);
INSERT INTO clerk (name, store_id) VALUES ('name 0006', 6);
INSERT INTO clerk (name, store_id) VALUES ('name 0007', 7);
INSERT INTO clerk (name, store_id) VALUES ('name 0008', 8);
INSERT INTO clerk (name, store_id) VALUES ('name 0009', 9);
INSERT INTO clerk (name, store_id) VALUES ('name 0010', 10);
INSERT INTO clerk (name, store_id) VALUES ('name 0011', 11);
INSERT INTO clerk (name, store_id) VALUES ('name 0012', 12);
INSERT INTO clerk (name, store_id) VALUES ('name 0013', 13);
INSERT INTO clerk (name, store_id) VALUES ('name 0014', 14);
INSERT INTO clerk (name, store_id) VALUES ('name 0015', 15);
INSERT INTO clerk (name, store_id) VALUES ('name 0016', 16);
INSERT INTO clerk (name, store_id) VALUES ('name 0017', 17);
INSERT INTO clerk (name, store_id) VALUES ('name 0018', 18);
INSERT INTO clerk (name, store_id) VALUES ('name 0019', 19);
INSERT INTO clerk (name, store_id) VALUES ('name 0020', 20);
INSERT INTO clerk (name, store_id) VALUES ('name 0021', 21);
INSERT INTO clerk (name, store_id) VALUES ('name 0022', 22);
INSERT INTO clerk (name, store_id) VALUES ('name 0023', 23);
INSERT INTO clerk (name, store_id) VALUES ('name 0024', 24);
INSERT INTO clerk (name, store_id) VALUES ('name 0025', 25);
INSERT INTO clerk (name, store_id) VALUES ('name 0026', 26);
INSERT INTO clerk (name, store_id) VALUES ('name 0027', 27);
INSERT INTO clerk (name, store_id) VALUES ('name 0028', 28);
INSERT INTO clerk (name, store_id) VALUES ('name 0029', 29);
INSERT INTO clerk (name, store_id) VALUES ('name 0030', 30);
INSERT INTO clerk (name, store_id) VALUES ('name 0031', 31);
INSERT INTO clerk (name, store_id) VALUES ('name 0032', 32);
INSERT INTO clerk (name, store_id) VALUES ('name 0033', 33);
INSERT INTO clerk (name, store_id) VALUES ('name 0034', 34);
INSERT INTO clerk (name, store_id) VALUES ('name 0035', 35);
INSERT INTO clerk (name, store_id) VALUES ('name 0036', 36);
INSERT INTO clerk (name, store_id) VALUES ('name 0037', 37);
INSERT INTO clerk (name, store_id) VALUES ('name 0038', 38);
INSERT INTO clerk (name, store_id) VALUES ('name 0039', 39);
INSERT INTO clerk (name, store_id) VALUES ('name 0040', 40);
INSERT INTO clerk (name, store_id) VALUES ('name 0041', 41);
INSERT INTO clerk (name, store_id) VALUES ('name 0042', 42);
INSERT INTO clerk (name, store_id) VALUES ('name 0043', 43);
INSERT INTO clerk (name, store_id) VALUES ('name 0044', 44);
INSERT INTO clerk (name, store_id) VALUES ('name 0045', 45);
INSERT INTO clerk (name, store_id) VALUES ('name 0046', 46);
INSERT INTO clerk (name, store_id) VALUES ('name 0047', 47);
INSERT INTO clerk (name, store_id) VALUES ('name 0048', 48);
INSERT INTO clerk (name, store_id) VALUES ('name 0049', 49);
INSERT INTO clerk (name, store_id) VALUES ('name 0050', 50);
INSERT INTO clerk (name, store_id) VALUES ('name 0051', 1);
INSERT INTO clerk (name, store_id) VALUES ('name 0052', 2);
INSERT INTO clerk (name, store_id) VALUES ('name 0053', 3);
INSERT INTO clerk (name, store_id) VALUES ('name 0054', 4);
INSERT INTO clerk (name, store_id) VALUES ('name 0055', 5);
INSERT INTO clerk (name, store_id) VALUES ('name 0056', 6);
INSERT INTO clerk (name, store_id) VALUES ('name 0057', 7);
INSERT INTO clerk (name, store_id) VALUES ('name 0058', 8);
INSERT INTO clerk (name, store_id) VALUES ('name 0059', 9);
INSERT INTO clerk (name, store_id) VALUES ('name 0060', 10);
INSERT INTO clerk (name, store_id) VALUES ('name 0061', 11);
INSERT INTO clerk (name, store_id) VALUES ('name 0062', 12);
INSERT INTO clerk (name, store_id) VALUES ('name 0063', 13);
INSERT INTO clerk (name, store_id) VALUES ('name 0064', 14);
INSERT INTO clerk (name, store_id) VALUES ('name 0065', 15);
INSERT INTO clerk (name, store_id) VALUES ('name 0066', 16);
INSERT INTO clerk (name, store_id) VALUES ('name 0067', 17);
INSERT INTO clerk (name, store_id) VALUES ('name 0068', 18);
INSERT INTO clerk (name, store_id) VALUES ('name 0069', 19);
INSERT INTO clerk (name, store_id) VALUES ('name 0070', 20);
INSERT INTO clerk (name, store_id) VALUES ('name 0071', 21);
INSERT INTO clerk (name, store_id) VALUES ('name 0072', 22);
INSERT INTO clerk (name, store_id) VALUES ('name 0073', 23);
INSERT INTO clerk (name, store_id) VALUES ('name 0074', 24);
INSERT INTO clerk (name, store_id) VALUES ('name 0075', 25);
INSERT INTO clerk (name, store_id) VALUES ('name 0076', 26);
INSERT INTO clerk (name, store_id) VALUES ('name 0077', 27);
INSERT INTO clerk (name, store_id) VALUES ('name 0078', 28);
INSERT INTO clerk (name, store_id) VALUES ('name 0079', 29);
INSERT INTO clerk (name, store_id) VALUES ('name 0080', 30);
INSERT INTO clerk (name, store_id) VALUES ('name 0081', 31);
INSERT INTO clerk (name, store_id) VALUES ('name 0082', 32);
INSERT INTO clerk (name, store_id) VALUES ('name 0083', 33);
INSERT INTO clerk (name, store_id) VALUES ('name 0084', 34);
INSERT INTO clerk (name, store_id) VALUES ('name 0085', 35);
INSERT INTO clerk (name, store_id) VALUES ('name 0086', 36);
INSERT INTO clerk (name, store_id) VALUES ('name 0087', 37);
INSERT INTO clerk (name, store_id) VALUES ('name 0088', 38);
INSERT INTO clerk (name, store_id) VALUES ('name 0089', 39);
INSERT INTO clerk (name, store_id) VALUES ('name 0090', 40);
INSERT INTO clerk (name, store_id) VALUES ('name 0091', 41);
INSERT INTO clerk (name, store_id) VALUES ('name 0092', 42);
INSERT INTO clerk (name, store_id) VALUES ('name 0093', 43);
INSERT INTO clerk (name, store_id) VALUES ('name 0094', 44);
INSERT INTO clerk (name, store_id) VALUES ('name 0095', 45);
INSERT INTO clerk (name, store_id) VALUES ('name 0096', 46);
INSERT INTO clerk (name, store_id) VALUES ('name 0097', 47);
INSERT INTO clerk (name, store_id) VALUES ('name 0098', 48);
INSERT INTO clerk (name, store_id) VALUES ('name 0099', 49);
INSERT INTO clerk (name, store_id) VALUES ('name 0100', 50);
INSERT INTO clerk (name, store_id) VALUES ('name 0101', 1);
INSERT INTO clerk (name, store_id) VALUES ('name 0102', 2);
INSERT INTO clerk (name, store_id) VALUES ('name 0103', 3);
INSERT INTO clerk (name, store_id) VALUES ('name 0104', 4);
INSERT INTO clerk (name, store_id) VALUES ('name 0105', 5);
INSERT INTO clerk (name, store_id) VALUES ('name 0106', 6);
INSERT INTO clerk (name, store_id) VALUES ('name 0107', 7);
INSERT INTO clerk (name, store_id) VALUES ('name 0108', 8);
INSERT INTO clerk (name, store_id) VALUES ('name 0109', 9);
INSERT INTO clerk (name, store_id) VALUES ('name 0110', 10);
INSERT INTO clerk (name, store_id) VALUES ('name 0111', 11);
INSERT INTO clerk (name, store_id) VALUES ('name 0112', 12);
INSERT INTO clerk (name, store_id) VALUES ('name 0113', 13);
INSERT INTO clerk (name, store_id) VALUES ('name 0114', 14);
INSERT INTO clerk (name, store_id) VALUES ('name 0115', 15);
INSERT INTO clerk (name, store_id) VALUES ('name 0116', 16);
INSERT INTO clerk (name, store_id) VALUES ('name 0117', 17);
INSERT INTO clerk (name, store_id) VALUES ('name 0118', 18);
INSERT INTO clerk (name, store_id) VALUES ('name 0119', 19);
INSERT INTO clerk (name, store_id) VALUES ('name 0120', 20);
INSERT INTO clerk (name, store_id) VALUES ('name 0121', 21);
INSERT INTO clerk (name, store_id) VALUES ('name 0122', 22);
INSERT INTO clerk (name, store_id) VALUES ('name 0123', 23);
INSERT INTO clerk (name, store_id) VALUES ('name 0124', 24);
INSERT INTO clerk (name, store_id) VALUES ('name 0125', 25);
INSERT INTO clerk (name, store_id) VALUES ('name 0126', 26);
INSERT INTO clerk (name, store_id) VALUES ('name 0127', 27);
INSERT INTO clerk (name, store_id) VALUES ('name 0128', 28);
INSERT INTO clerk (name, store_id) VALUES ('name 0129', 29);
INSERT INTO clerk (name, store_id) VALUES ('name 0130', 30);
INSERT INTO clerk (name, store_id) VALUES ('name 0131', 31);
INSERT INTO clerk (name, store_id) VALUES ('name 0132', 32);
INSERT INTO clerk (name, store_id) VALUES ('name 0133', 33);
INSERT INTO clerk (name, store_id) VALUES ('name 0134', 34);
INSERT INTO clerk (name, store_id) VALUES ('name 0135', 35);
INSERT INTO clerk (name, store_id) VALUES ('name 0136', 36);
INSERT INTO clerk (name, store_id) VALUES ('name 0137', 37);
INSERT INTO clerk (name, store_id) VALUES ('name 0138', 38);
INSERT INTO clerk (name, store_id) VALUES ('name 0139', 39);
INSERT INTO clerk (name, store_id) VALUES ('name 0140', 40);
INSERT INTO clerk (name, store_id) VALUES ('name 0141', 41);
INSERT INTO clerk (name, store_id) VALUES ('name 0142', 42);
INSERT INTO clerk (name, store_id) VALUES ('name 0143', 43);
INSERT INTO clerk (name, store_id) VALUES ('name 0144', 44);
INSERT INTO clerk (name, store_id) VALUES ('name 0145', 45);
INSERT INTO clerk (name, store_id) VALUES ('name 0146', 46);
INSERT INTO clerk (name, store_id) VALUES ('name 0147', 47);
INSERT INTO clerk (name, store_id) VALUES ('name 0148', 48);
INSERT INTO clerk (name, store_id) VALUES ('name 0149', 49);
INSERT INTO clerk (name, store_id) VALUES ('name 0150', 50);
INSERT INTO clerk (name, store_id) VALUES ('name 0151', 1);
INSERT INTO clerk (name, store_id) VALUES ('name 0152', 2);
INSERT INTO clerk (name, store_id) VALUES ('name 0153', 3);
INSERT INTO clerk (name, store_id) VALUES ('name 0154', 4);
INSERT INTO clerk (name, store_id) VALUES ('name 0155', 5);
INSERT INTO clerk (name, store_id) VALUES ('name 0156', 6);
INSERT INTO clerk (name, store_id) VALUES ('name 0157', 7);
INSERT INTO clerk (name, store_id) VALUES ('name 0158', 8);
INSERT INTO clerk (name, store_id) VALUES ('name 0159', 9);
INSERT INTO clerk (name, store_id) VALUES ('name 0160', 10);
INSERT INTO clerk (name, store_id) VALUES ('name 0161', 11);
INSERT INTO clerk (name, store_id) VALUES ('name 0162', 12);
INSERT INTO clerk (name, store_id) VALUES ('name 0163', 13);
INSERT INTO clerk (name, store_id) VALUES ('name 0164', 14);
INSERT INTO clerk (name, store_id) VALUES ('name 0165', 15);
INSERT INTO clerk (name, store_id) VALUES ('name 0166', 16);
INSERT INTO clerk (name, store_id) VALUES ('name 0167', 17);
INSERT INTO clerk (name, store_id) VALUES ('name 0168', 18);
INSERT INTO clerk (name, store_id) VALUES ('name 0169', 19);
INSERT INTO clerk (name, store_id) VALUES ('name 0170', 20);
INSERT INTO clerk (name, store_id) VALUES ('name 0171', 21);
INSERT INTO clerk (name, store_id) VALUES ('name 0172', 22);
INSERT INTO clerk (name, store_id) VALUES ('name 0173', 23);
INSERT INTO clerk (name, store_id) VALUES ('name 0174', 24);
INSERT INTO clerk (name, store_id) VALUES ('name 0175', 25);
INSERT INTO clerk (name, store_id) VALUES ('name 0176', 26);
INSERT INTO clerk (name, store_id) VALUES ('name 0177', 27);
INSERT INTO clerk (name, store_id) VALUES ('name 0178', 28);
INSERT INTO clerk (name, store_id) VALUES ('name 0179', 29);
INSERT INTO clerk (name, store_id) VALUES ('name 0180', 30);
INSERT INTO clerk (name, store_id) VALUES ('name 0181', 31);
INSERT INTO clerk (name, store_id) VALUES ('name 0182', 32);
INSERT INTO clerk (name, store_id) VALUES ('name 0183', 33);
INSERT INTO clerk (name, store_id) VALUES ('name 0184', 34);
INSERT INTO clerk (name, store_id) VALUES ('name 0185', 35);
INSERT INTO clerk (name, store_id) VALUES ('name 0186', 36);
INSERT INTO clerk (name, store_id) VALUES ('name 0187', 37);
INSERT INTO clerk (name, store_id) VALUES ('name 0188', 38);
INSERT INTO clerk (name, store_id) VALUES ('name 0189', 39);
INSERT INTO clerk (name, store_id) VALUES ('name 0190', 40);
INSERT INTO clerk (name, store_id) VALUES ('name 0191', 41);
INSERT INTO clerk (name, store_id) VALUES ('name 0192', 42);
INSERT INTO clerk (name, store_id) VALUES ('name 0193', 43);
INSERT INTO clerk (name, store_id) VALUES ('name 0194', 44);
INSERT INTO clerk (name, store_id) VALUES ('name 0195', 45);
INSERT INTO clerk (name, store_id) VALUES ('name 0196', 46);
INSERT INTO clerk (name, store_id) VALUES ('name 0197', 47);
INSERT INTO clerk (name, store_id) VALUES ('name 0198', 48);
INSERT INTO clerk (name, store_id) VALUES ('name 0199', 49);
INSERT INTO clerk (name, store_id) VALUES ('name 0200', 50);
INSERT INTO clerk (name, store_id) VALUES ('name 0201', 1);
INSERT INTO clerk (name, store_id) VALUES ('name 0202', 2);
INSERT INTO clerk (name, store_id) VALUES ('name 0203', 3);
INSERT INTO clerk (name, store_id) VALUES ('name 0204', 4);
INSERT INTO clerk (name, store_id) VALUES ('name 0205', 5);
INSERT INTO clerk (name, store_id) VALUES ('name 0206', 6);
INSERT INTO clerk (name, store_id) VALUES ('name 0207', 7);
INSERT INTO clerk (name, store_id) VALUES ('name 0208', 8);
INSERT INTO clerk (name, store_id) VALUES ('name 0209', 9);
INSERT INTO clerk (name, store_id) VALUES ('name 0210', 10);
INSERT INTO clerk (name, store_id) VALUES ('name 0211', 11);
INSERT INTO clerk (name, store_id) VALUES ('name 0212', 12);
INSERT INTO clerk (name, store_id) VALUES ('name 0213', 13);
INSERT INTO clerk (name, store_id) VALUES ('name 0214', 14);
INSERT INTO clerk (name, store_id) VALUES ('name 0215', 15);
INSERT INTO clerk (name, store_id) VALUES ('name 0216', 16);
INSERT INTO clerk (name, store_id) VALUES ('name 0217', 17);
INSERT INTO clerk (name, store_id) VALUES ('name 0218', 18);
INSERT INTO clerk (name, store_id) VALUES ('name 0219', 19);
INSERT INTO clerk (name, store_id) VALUES ('name 0220', 20);
INSERT INTO clerk (name, store_id) VALUES ('name 0221', 21);
INSERT INTO clerk (name, store_id) VALUES ('name 0222', 22);
INSERT INTO clerk (name, store_id) VALUES ('name 0223', 23);
INSERT INTO clerk (name, store_id) VALUES ('name 0224', 24);
INSERT INTO clerk (name, store_id) VALUES ('name 0225', 25);
INSERT INTO clerk (name, store_id) VALUES ('name 0226', 26);
INSERT INTO clerk (name, store_id) VALUES ('name 0227', 27);
INSERT INTO clerk (name, store_id) VALUES ('name 0228', 28);
INSERT INTO clerk (name, store_id) VALUES ('name 0229', 29);
INSERT INTO clerk (name, store_id) VALUES ('name 0230', 30);
INSERT INTO clerk (name, store_id) VALUES ('name 0231', 31);
INSERT INTO clerk (name, store_id) VALUES ('name 0232', 32);
INSERT INTO clerk (name, store_id) VALUES ('name 0233', 33);
INSERT INTO clerk (name, store_id) VALUES ('name 0234', 34);
INSERT INTO clerk (name, store_id) VALUES ('name 0235', 35);
INSERT INTO clerk (name, store_id) VALUES ('name 0236', 36);
INSERT INTO clerk (name, store_id) VALUES ('name 0237', 37);
INSERT INTO clerk (name, store_id) VALUES ('name 0238', 38);
INSERT INTO clerk (name, store_id) VALUES ('name 0239', 39);
INSERT INTO clerk (name, store_id) VALUES ('name 0240', 40);
INSERT INTO clerk (name, store_id) VALUES ('name 0241', 41);
INSERT INTO clerk (name, store_id) VALUES ('name 0242', 42);
INSERT INTO clerk (name, store_id) VALUES ('name 0243', 43);
INSERT INTO clerk (name, store_id) VALUES ('name 0244', 44);
INSERT INTO clerk (name, store_id) VALUES ('name 0245', 45);
INSERT INTO clerk (name, store_id) VALUES ('name 0246', 46);
INSERT INTO clerk (name, store_id) VALUES ('name 0247', 47);
INSERT INTO clerk (name, store_id) VALUES ('name 0248', 48);
INSERT INTO clerk (name, store_id) VALUES ('name 0249', 49);
INSERT INTO clerk (name, store_id) VALUES ('name 0250', 50);
INSERT INTO clerk (name, store_id) VALUES ('name 0251', 1);
INSERT INTO clerk (name, store_id) VALUES ('name 0252', 2);
INSERT INTO clerk (name, store_id) VALUES ('name 0253', 3);
INSERT INTO clerk (name, store_id) VALUES ('name 0254', 4);
INSERT INTO clerk (name, store_id) VALUES ('name 0255', 5);
INSERT INTO clerk (name, store_id) VALUES ('name 0256', 6);
INSERT INTO clerk (name, store_id) VALUES ('name 0257', 7);
INSERT INTO clerk (name, store_id) VALUES ('name 0258', 8);
INSERT INTO clerk (name, store_id) VALUES ('name 0259', 9);
INSERT INTO clerk (name, store_id) VALUES ('name 0260', 10);
INSERT INTO clerk (name, store_id) VALUES ('name 0261', 11);
INSERT INTO clerk (name, store_id) VALUES ('name 0262', 12);
INSERT INTO clerk (name, store_id) VALUES ('name 0263', 13);
INSERT INTO clerk (name, store_id) VALUES ('name 0264', 14);
INSERT INTO clerk (name, store_id) VALUES ('name 0265', 15);
INSERT INTO clerk (name, store_id) VALUES ('name 0266', 16);
INSERT INTO clerk (name, store_id) VALUES ('name 0267', 17);
INSERT INTO clerk (name, store_id) VALUES ('name 0268', 18);
INSERT INTO clerk (name, store_id) VALUES ('name 0269', 19);
INSERT INTO clerk (name, store_id) VALUES ('name 0270', 20);
INSERT INTO clerk (name, store_id) VALUES ('name 0271', 21);
INSERT INTO clerk (name, store_id) VALUES ('name 0272', 22);
INSERT INTO clerk (name, store_id) VALUES ('name 0273', 23);
INSERT INTO clerk (name, store_id) VALUES ('name 0274', 24);
INSERT INTO clerk (name, store_id) VALUES ('name 0275', 25);
INSERT INTO clerk (name, store_id) VALUES ('name 0276', 26);
INSERT INTO clerk (name, store_id) VALUES ('name 0277', 27);
INSERT INTO clerk (name, store_id) VALUES ('name 0278', 28);
INSERT INTO clerk (name, store_id) VALUES ('name 0279', 29);
INSERT INTO clerk (name, store_id) VALUES ('name 0280', 30);
INSERT INTO clerk (name, store_id) VALUES ('name 0281', 31);
INSERT INTO clerk (name, store_id) VALUES ('name 0282', 32);
INSERT INTO clerk (name, store_id) VALUES ('name 0283', 33);
INSERT INTO clerk (name, store_id) VALUES ('name 0284', 34);
INSERT INTO clerk (name, store_id) VALUES ('name 0285', 35);
INSERT INTO clerk (name, store_id) VALUES ('name 0286', 36);
INSERT INTO clerk (name, store_id) VALUES ('name 0287', 37);
INSERT INTO clerk (name, store_id) VALUES ('name 0288', 38);
INSERT INTO clerk (name, store_id) VALUES ('name 0289', 39);
INSERT INTO clerk (name, store_id) VALUES ('name 0290', 40);
INSERT INTO clerk (name, store_id) VALUES ('name 0291', 41);
INSERT INTO clerk (name, store_id) VALUES ('name 0292', 42);
INSERT INTO clerk (name, store_id) VALUES ('name 0293', 43);
INSERT INTO clerk (name, store_id) VALUES ('name 0294', 44);
INSERT INTO clerk (name, store_id) VALUES ('name 0295', 45);
INSERT INTO clerk (name, store_id) VALUES ('name 0296', 46);
INSERT INTO clerk (name, store_id) VALUES ('name 0297', 47);
INSERT INTO clerk (name, store_id) VALUES ('name 0298', 48);
INSERT INTO clerk (name, store_id) VALUES ('name 0299', 49);
INSERT INTO clerk (name, store_id) VALUES ('name 0300', 50);
INSERT INTO clerk (name, store_id) VALUES ('name 0301', 1);
INSERT INTO clerk (name, store_id) VALUES ('name 0302', 2);
INSERT INTO clerk (name, store_id) VALUES ('name 0303', 3);
INSERT INTO clerk (name, store_id) VALUES ('name 0304', 4);
INSERT INTO clerk (name, store_id) VALUES ('name 0305', 5);
INSERT INTO clerk (name, store_id) VALUES ('name 0306', 6);
INSERT INTO clerk (name, store_id) VALUES ('name 0307', 7);
INSERT INTO clerk (name, store_id) VALUES ('name 0308', 8);
INSERT INTO clerk (name, store_id) VALUES ('name 0309', 9);
INSERT INTO clerk (name, store_id) VALUES ('name 0310', 10);
INSERT INTO clerk (name, store_id) VALUES ('name 0311', 11);
INSERT INTO clerk (name, store_id) VALUES ('name 0312', 12);
INSERT INTO clerk (name, store_id) VALUES ('name 0313', 13);
INSERT INTO clerk (name, store_id) VALUES ('name 0314', 14);
INSERT INTO clerk (name, store_id) VALUES ('name 0315', 15);
INSERT INTO clerk (name, store_id) VALUES ('name 0316', 16);
INSERT INTO clerk (name, store_id) VALUES ('name 0317', 17);
INSERT INTO clerk (name, store_id) VALUES ('name 0318', 18);
INSERT INTO clerk (name, store_id) VALUES ('name 0319', 19);
INSERT INTO clerk (name, store_id) VALUES ('name 0320', 20);
INSERT INTO clerk (name, store_id) VALUES ('name 0321', 21);
INSERT INTO clerk (name, store_id) VALUES ('name 0322', 22);
INSERT INTO clerk (name, store_id) VALUES ('name 0323', 23);
INSERT INTO clerk (name, store_id) VALUES ('name 0324', 24);
INSERT INTO clerk (name, store_id) VALUES ('name 0325', 25);
INSERT INTO clerk (name, store_id) VALUES ('name 0326', 26);
INSERT INTO clerk (name, store_id) VALUES ('name 0327', 27);
INSERT INTO clerk (name, store_id) VALUES ('name 0328', 28);
INSERT INTO clerk (name, store_id) VALUES ('name 0329', 29);
INSERT INTO clerk (name, store_id) VALUES ('name 0330', 30);
INSERT INTO clerk (name, store_id) VALUES ('name 0331', 31);
INSERT INTO clerk (name, store_id) VALUES ('name 0332', 32);
INSERT INTO clerk (name, store_id) VALUES ('name 0333', 33);
INSERT INTO clerk (name, store_id) VALUES ('name 0334', 34);
INSERT INTO clerk (name, store_id) VALUES ('name 0335', 35);
INSERT INTO clerk (name, store_id) VALUES ('name 0336', 36);
INSERT INTO clerk (name, store_id) VALUES ('name 0337', 37);
INSERT INTO clerk (name, store_id) VALUES ('name 0338', 38);
INSERT INTO clerk (name, store_id) VALUES ('name 0339', 39);
INSERT INTO clerk (name, store_id) VALUES ('name 0340', 40);
INSERT INTO clerk (name, store_id) VALUES ('name 0341', 41);
INSERT INTO clerk (name, store_id) VALUES ('name 0342', 42);
INSERT INTO clerk (name, store_id) VALUES ('name 0343', 43);
INSERT INTO clerk (name, store_id) VALUES ('name 0344', 44);
INSERT INTO clerk (name, store_id) VALUES ('name 0345', 45);
INSERT INTO clerk (name, store_id) VALUES ('name 0346', 46);
INSERT INTO clerk (name, store_id) VALUES ('name 0347', 47);
INSERT INTO clerk (name, store_id) VALUES ('name 0348', 48);
INSERT INTO clerk (name, store_id) VALUES ('name 0349', 49);
INSERT INTO clerk (name, store_id) VALUES ('name 0350', 50);
INSERT INTO clerk (name, store_id) VALUES ('name 0351', 1);
INSERT INTO clerk (name, store_id) VALUES ('name 0352', 2);
INSERT INTO clerk (name, store_id) VALUES ('name 0353', 3);
INSERT INTO clerk (name, store_id) VALUES ('name 0354', 4);
INSERT INTO clerk (name, store_id) VALUES ('name 0355', 5);
INSERT INTO clerk (name, store_id) VALUES ('name 0356', 6);
INSERT INTO clerk (name, store_id) VALUES ('name 0357', 7);
INSERT INTO clerk (name, store_id) VALUES ('name 0358', 8);
INSERT INTO clerk (name, store_id) VALUES ('name 0359', 9);
INSERT INTO clerk (name, store_id) VALUES ('name 0360', 10);
INSERT INTO clerk (name, store_id) VALUES ('name 0361', 11);
INSERT INTO clerk (name, store_id) VALUES ('name 0362', 12);
INSERT INTO clerk (name, store_id) VALUES ('name 0363', 13);
INSERT INTO clerk (name, store_id) VALUES ('name 0364', 14);
INSERT INTO clerk (name, store_id) VALUES ('name 0365', 15);
INSERT INTO clerk (name, store_id) VALUES ('name 0366', 16);
INSERT INTO clerk (name, store_id) VALUES ('name 0367', 17);
INSERT INTO clerk (name, store_id) VALUES ('name 0368', 18);
INSERT INTO clerk (name, store_id) VALUES ('name 0369', 19);
INSERT INTO clerk (name, store_id) VALUES ('name 0370', 20);
INSERT INTO clerk (name, store_id) VALUES ('name 0371', 21);
INSERT INTO clerk (name, store_id) VALUES ('name 0372', 22);
INSERT INTO clerk (name, store_id) VALUES ('name 0373', 23);
INSERT INTO clerk (name, store_id) VALUES ('name 0374', 24);
INSERT INTO clerk (name, store_id) VALUES ('name 0375', 25);
INSERT INTO clerk (name, store_id) VALUES ('name 0376', 26);
INSERT INTO clerk (name, store_id) VALUES ('name 0377', 27);
INSERT INTO clerk (name, store_id) VALUES ('name 0378', 28);
INSERT INTO clerk (name, store_id) VALUES ('name 0379', 29);
INSERT INTO clerk (name, store_id) VALUES ('name 0380', 30);
INSERT INTO clerk (name, store_id) VALUES ('name 0381', 31);
INSERT INTO clerk (name, store_id) VALUES ('name 0382', 32);
INSERT INTO clerk (name, store_id) VALUES ('name 0383', 33);
INSERT INTO clerk (name, store_id) VALUES ('name 0384', 34);
INSERT INTO clerk (name, store_id) VALUES ('name 0385', 35);
INSERT INTO clerk (name, store_id) VALUES ('name 0386', 36);
INSERT INTO clerk (name, store_id) VALUES ('name 0387', 37);
INSERT INTO clerk (name, store_id) VALUES ('name 0388', 38);
INSERT INTO clerk (name, store_id) VALUES ('name 0389', 39);
INSERT INTO clerk (name, store_id) VALUES ('name 0390', 40);
INSERT INTO clerk (name, store_id) VALUES ('name 0391', 41);
INSERT INTO clerk (name, store_id) VALUES ('name 0392', 42);
INSERT INTO clerk (name, store_id) VALUES ('name 0393', 43);
INSERT INTO clerk (name, store_id) VALUES ('name 0394', 44);
INSERT INTO clerk (name, store_id) VALUES ('name 0395', 45);
INSERT INTO clerk (name, store_id) VALUES ('name 0396', 46);
INSERT INTO clerk (name, store_id) VALUES ('name 0397', 47);
INSERT INTO clerk (name, store_id) VALUES ('name 0398', 48);
INSERT INTO clerk (name, store_id) VALUES ('name 0399', 49);
INSERT INTO clerk (name, store_id) VALUES ('name 0400', 50);